/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_i1_reg_CFTP */

#ifndef _Included_org_i1_reg_CFTP
#define _Included_org_i1_reg_CFTP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_i1_reg_CFTP
 * Method:    FTPDownload
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_i1_reg_CFTP_FTPDownload
  (JNIEnv * env, jobject, jstring sUrl, jstring sFilename, jstring sUser, jstring sPassword, jlong lShow_Download, jstring sFile_Type);

/*
 * Class:     org_i1_reg_CFTP
 * Method:    FTPUpload
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_i1_reg_CFTP_FTPUpload
  (JNIEnv * env, jobject, jstring sUrl, jstring sLocal_Filename, jstring sUser, jstring sPassword);

#ifdef __cplusplus
}
#endif
#endif
